---
# Install vim task

- name: "Install vim with yum"         # task name for standard output
  yum:                                 # Ansible module to use
    name: vim                            # package to install
    state: latest                        # install latest version
  become: yes                          # escelate users privilege for task
  when: ansible_os_family == "RedHat"  # only run on RedHat family distros

- name: "Install vim with apt"
  apt:
    name: vim
    state: latest
  become: yes
  when: ansible_os_family == "Debian"
